### PR TITLE
#689: DeduplicateAction: schema evolution if mergeModeEnable=true and updateCapturedColumnOnlyWhenChanged=true

### LINKED ISSUE #689: DeduplicateAction: problems with schema evolution if mergeModeEnable=true and updateCapturedColumnOnlyWhenChanged=true
**Describe the bug**
Error with schema evolution if mergeModeEnable=true and updateCapturedColumnOnlyWhenChanged=true, and there is a schema evolution, e.g. new columns:

`[DeduplicateAction]: Exec failed with AnalysisException: cannot resolve existing.<colX> in UPDATE condition given columns existing.<colA>, ..., new.<colA>, ...`

**Expected behavior**
Schema evolution doesn't fail.

### PR DESCRIPTION
**Pull request by zzeekk**
closes #689 

### What changes are included in the pull request?
Fix problems with Deduplicate Action if mergeModeEnable=true and updateCapturedColumnOnlyWhenChanged=true:
- fix comparing new columns in update condition of merge statement
- fix comparing null values correctly in update condition of merge statement

### Why are the changes needed?
Fix error with schema evolution if mergeModeEnable=true and updateCapturedColumnOnlyWhenChanged=true:
`[DeduplicateAction]: Exec failed with AnalysisException: cannot resolve existing.<colX> in UPDATE condition given columns existing.<colA>, ..., new.<colA>, ...`

### CODE REVIEW

File: sdl-core/src/main/scala/io/smartdatalake/workflow/action/DeduplicateAction.scala [hunk 1]
```diff
@@ -103,7 +104,12 @@ case class DeduplicateAction(override val id: ActionId,
...
     assert(output.isInstanceOf[CanMergeDataFrame], s"($id) output DataObject must support SaveMode.Merge (implement CanMergeDataFrame) if mergeModeEnable = true")
     // customize update condition
-    val updateCondition = if (updateCapturedColumnOnlyWhenChanged) Some(checkRecordChangedColumns.map(c => s"existing.$c != new.$c").mkString(" or "))
+    val updateCondition = if (updateCapturedColumnOnlyWhenChanged) {
+      val (colsToUpdate, colsNew) = checkRecordChangedColumns.partition(outputCols.contains)
+      val colsToUpdateConditions = colsToUpdate.map(c => s"existing.$c != new.$c or (existing.$c is not null and new.$c is null) or (existing.$c is null and new.$c is not null)") // comparing equality including null is complicated with standard sql
+      val colsNewCondition = colsNew.map(c => s"new.$c is not null") // null is the default value of the new column, we need to update if the value in new data is not null
+      Some((colsToUpdateConditions ++ colsNewCondition).mkString(" or "))
+    }
     else None
```
Comment (iliassoto) [inline sdl-core/src/main/scala/io/smartdatalake/workflow/action/DeduplicateAction.scala:113]: Is this "None" an error?

Comment (zzeekk) [reply sdl-core/src/main/scala/io/smartdatalake/workflow/action/DeduplicateAction.scala:113]: No, it's related to "if (updateCapturedColumnOnlyWhenChanged)" and has not changed in this PR.

**Review by iliassoto — APPROVED** [review]
