### PR TITLE
Fix #872, #873

### LINKED ISSUE #872: SubFeed metrics keep input values if skipped
**Describe the bug**
Output SubFeeds keep metrics from Input SubFeeds when action is Skipped

**To Reproduce**
2 Actions, second is skipped because there is no-data.
When debugging it seems that SubFeed metrics are not cleared, but keep the value from the Input SubFeed, e.g. from the previous Actions output SubFeed.

When an Action is executed successfully or fails because of expectation validation failure, each output SubFeeds metrics are overwritten. But if the Action is skipped this seems not to be the case.

**Expected behavior**
Output SubFeeds metrics are cleared before execution is started.

### PR DESCRIPTION
**Pull request by zzeekk**
see #872, #873

### CODE REVIEW

**Review by Geheiner — APPROVED** [review]
Looks good!

File: sdl-core/src/main/scala/io/smartdatalake/workflow/action/DataFrameActionImpl.scala [hunk 1]
```diff
@@ -553,8 +553,4 @@ abstract class DataFrameActionImpl extends ActionSubFeedsImpl[DataFrameSubFeed]
         }
     }
   }
-
-  override def postExecFailed(implicit context: ActionPipelineContext): Unit = {
-    super.postExecFailed
```
Comment (Geheiner) [inline sdl-core/src/main/scala/io/smartdatalake/workflow/action/DataFrameActionImpl.scala:558]: thanks for removing this, now there is less risk that someone overrides it and then wonders why the metrics are not executed.
